export const ANNOUNCE_LIST_REQUEST = 'ANNOUNCE_LIST_REQUEST'
export const ANNOUNCE_LIST_SUCCESS = 'ANNOUNCE_LIST_SUCCESS'
export const ANNOUNCE_LIST_FAIL = 'ANNOUNCE_LIST_FAIL'

export const ANNOUNCE_DETAILS_REQUEST = 'ANNOUNCE_DETAILS_REQUEST'
export const ANNOUNCE_DETAILS_SUCCESS = 'ANNOUNCE_DETAILS_SUCCESS'
export const ANNOUNCE_DETAILS_FAIL = 'ANNOUNCE_DETAILS_FAIL'

export const ANNOUNCE_DELETE_REQUEST = 'ANNOUNCE_DELETE_REQUEST'
export const ANNOUNCE_DELETE_SUCCESS = 'ANNOUNCE_DELETE_SUCCESS'
export const ANNOUNCE_DELETE_FAIL = 'ANNOUNCE_DELETE_FAIL'

export const ANNOUNCE_CREATE_REQUEST = 'ANNOUNCE_CREATE_REQUEST'
export const ANNOUNCE_CREATE_SUCCESS = 'ANNOUNCE_CREATE_SUCCESS'
export const ANNOUNCE_CREATE_FAIL = 'ANNOUNCE_CREATE_FAIL'
export const ANNOUNCE_CREATE_RESET = 'ANNOUNCE_CREATE_RESET'

export const ANNOUNCE_UPDATE_REQUEST = 'ANNOUNCE_UPDATE_REQUEST'
export const ANNOUNCE_UPDATE_SUCCESS = 'ANNOUNCE_UPDATE_SUCCESS'
export const ANNOUNCE_UPDATE_FAIL = 'ANNOUNCE_UPDATE_FAIL'
export const ANNOUNCE_UPDATE_RESET = 'ANNOUNCE_UPDATE_RESET'

export const ANNOUNCE_CREATE_REVIEW_REQUEST = 'ANNOUNCE_CREATE_REVIEW_REQUEST'
export const ANNOUNCE_CREATE_REVIEW_SUCCESS = 'ANNOUNCE_CREATE_REVIEW_SUCCESS'
export const ANNOUNCE_CREATE_REVIEW_FAIL = 'ANNOUNCE_CREATE_REVIEW_FAIL'
export const ANNOUNCE_CREATE_REVIEW_RESET = 'ANNOUNCE_CREATE_REVIEW_RESET'

export const ANNOUNCE_TOP_REQUEST = 'ANNOUNCE_TOP_REQUEST'
export const ANNOUNCE_TOP_SUCCESS = 'ANNOUNCE_TOP_SUCCESS'
export const ANNOUNCE_TOP_FAIL = 'ANNOUNCE_TOP_FAIL'

export const BANNER_LIST_REQUEST = 'BANNER_LIST_REQUEST'
export const BANNER_LIST_SUCCESS = 'BANNER_LIST_SUCCESS'
export const BANNER_LIST_FAIL = 'BANNER_LIST_FAIL'

export const TEXT_ANNOUNCE_CREATE_REQUEST = 'TEXT_ANNOUNCE_CREATE_REQUEST'
export const TEXT_ANNOUNCE_CREATE_SUCCESS = 'TEXT_ANNOUNCE_CREATE_SUCCESS'
export const TEXT_ANNOUNCE_CREATE_FAIL = 'TEXT_ANNOUNCE_CREATE_FAIL'
export const TEXT_ANNOUNCE_CREATE_RESET = 'TEXT_ANNOUNCE_CREATE_RESET'

export const TEXT_ANNOUNCE_LIST_REQUEST = 'TEXT_ANNOUNCE_LIST_REQUEST'
export const TEXT_ANNOUNCE_LIST_SUCCESS = 'TEXT_ANNOUNCE_LIST_SUCCESS'
export const TEXT_ANNOUNCE_LIST_FAIL = 'TEXT_ANNOUNCE_LIST_FAIL'

export const TEXT_ANNOUNCE_DELETE_REQUEST = 'TEXT_ANNOUNCE_DELETE_REQUEST'
export const TEXT_ANNOUNCE_DELETE_SUCCESS = 'TEXT_ANNOUNCE_DELETE_SUCCESS'
export const TEXT_ANNOUNCE_DELETE_FAIL = 'TEXT_ANNOUNCE_DELETE_FAIL'