export const BANK_ACCOUNT_LIST_REQUEST = 'BANK_ACCOUNT_LIST_REQUEST'
export const BANK_ACCOUNT_LIST_SUCCESS = 'BANK_ACCOUNT_LIST_SUCCESS'
export const BANK_ACCOUNT_LIST_FAIL = 'BANK_ACCOUNT_LIST_FAIL'

export const BANK_ACCOUNT_DETAILS_REQUEST = 'BANK_ACCOUNT_DETAILS_REQUEST'
export const BANK_ACCOUNT_DETAILS_SUCCESS = 'BANK_ACCOUNT_DETAILS_SUCCESS'
export const BANK_ACCOUNT_DETAILS_FAIL = 'BANK_ACCOUNT_DETAILS_FAIL'

export const BANK_ACCOUNT_DELETE_REQUEST = 'BANK_ACCOUNT_DELETE_REQUEST'
export const BANK_ACCOUNT_DELETE_SUCCESS = 'BANK_ACCOUNT_DELETE_SUCCESS'
export const BANK_ACCOUNT_DELETE_FAIL = 'BANK_ACCOUNT_DELETE_FAIL'

export const BANK_ACCOUNT_CREATE_REQUEST = 'BANK_ACCOUNT_CREATE_REQUEST'
export const BANK_ACCOUNT_CREATE_SUCCESS = 'BANK_ACCOUNT_CREATE_SUCCESS'
export const BANK_ACCOUNT_CREATE_FAIL = 'BANK_ACCOUNT_CREATE_FAIL'
export const BANK_ACCOUNT_CREATE_RESET = 'BANK_ACCOUNT_CREATE_RESET'

export const BANK_ACCOUNT_UPDATE_REQUEST = 'BANK_ACCOUNT_UPDATE_REQUEST'
export const BANK_ACCOUNT_UPDATE_SUCCESS = 'BANK_ACCOUNT_UPDATE_SUCCESS'
export const BANK_ACCOUNT_UPDATE_FAIL = 'BANK_ACCOUNT_UPDATE_FAIL'
export const BANK_ACCOUNT_UPDATE_RESET = 'BANK_ACCOUNT_UPDATE_RESET'

export const BANK_ACCOUNT_ALL_REQUEST = 'BANK_ACCOUNT_ALL_REQUEST'
export const BANK_ACCOUNT_ALL_SUCCESS = 'BANK_ACCOUNT_ALL_SUCCESS'
export const BANK_ACCOUNT_ALL_FAIL = 'BANK_ACCOUNT_ALL_FAIL'